export const enum Protocols {
  ZRX_STAKING = '0x Staking',
  AAVE = 'Aave',
  BALANCER = 'Balancer',
  BANCOR = 'Bancor',
  CHAI = 'Chai',
  COMPOUND = 'Compound',
  CURVE = 'Curve',
  DSR = 'Dai Savings Rate',
  DMM = 'DeFi Money Market',
  DYDX = 'dYdX',
  IDLE = 'Idle',
  IEARN_V2 = 'iearn.finance (v2)',
  IEARN_V3 = 'iearn.finance (v3)',
  MCD = 'Multi-Collateral Dai',
  PIEDAO = 'PieDAO',
  POOLTOGETHER = 'PoolTogether',
  SYNTHETIX = 'Synthetix',
  TOKENSETS = 'TokenSets',
  UNISWAP_V1 = 'Uniswap V1',
  UNISWAP_V2 = 'Uniswap V2',
}
