export const TokenAdapters = {
  AAVE: 'AToken',
  BALANCER: 'Balancer pool token',
  CHAI: 'Chai token',
  COMPOUND: 'CToken',
  CURVE: 'Curve pool token',
  ERC20: 'ERC20',
  IDLE: 'IdleToken',
  DMM: 'MToken',
  PIEDAO: 'PieDAO Pie Token',
  POOLTOGETHER: 'PoolTogether pool',
  TOKENSETS: 'SetToken',
  BANCOR: 'SmartToken',
  UNISWAP_V1: 'Uniswap V1 pool token',
  UNISWAP_V2: 'Uniswap V2 pool token',
  IEARN: 'YToken',
};
