export type RDBTransactionType =
  | "send"
  | "receive"
  | "trade"
  | "authorize"
  | "execution"
  | "deployment"
  | "cancel"
  | "deposit"
  | "withdraw"
  | "borrow"
  | "repay"
  | "stake"
  | "unstake"
  | "claim";
